name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install Poetry
        uses: abatilo/actions-poetry@v3


      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run Tests
        run: poetry run pytest tests/